server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /ecommerce
spring:
  profiles:
    active: local
  application:
    name: E-commerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "greenshop-ecommerce-secret-key-must-be-at-least-32-characters-long"
  valid-duration: 3600
  refreshable-duration: 86400

